### ISSUE TITLE
java.lang.ClassCastException: net.minecraft.world.gen.feature.ReplaceBlockConfig cannot be cast to net.minecraft.world.gen.feature.DecoratedFeatureConfig

### ISSUE THREAD

**Issue by JaisDK** [Voronoiii/BYG#28]
Hello,
In your DisklessDepositor class you are making the assumption that all GenerationStage.Decoration.UNDERGROUND_ORES feataures have a DecoratedFeatureConfig, but this is not necessarily true when having other mods installed. Can you please add a type check before casting to DecoratedFeatureConfig?

Full stack trace:

`Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.world.gen.feature.ReplaceBlockConfig cannot be cast to net.minecraft.world.gen.feature.DecoratedFeatureConfig
	at voronoiaoc.byg.common.world.worldtype.noise.simplex.chunkgen.DisklessDepositor.<init>(DisklessDepositor.java:31) ~[?:0.3.2-BETA] {re:classloading}
	at voronoiaoc.byg.common.world.worldtype.chunk.simplex.Simplex3DNoiseChunkGenerator.<init>(Simplex3DNoiseChunkGenerator.java:152) ~[?:0.3.2-BETA] {re:classloading}
	at voronoiaoc.byg.common.world.dimension.nether.chunk.BYGNetherChunkGenerator.<init>(BYGNetherChunkGenerator.java:22) ~[?:0.3.2-BETA] {re:classloading}
	at voronoiaoc.byg.common.world.dimension.nether.hooks.ClientNetherDimensionHook$$Lambda$6752/539657386.create(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.ChunkGeneratorType.create(ChunkGeneratorType.java:31) ~[?:?] {re:classloading}
	at voronoiaoc.byg.common.world.dimension.nether.hooks.ClientNetherDimensionHook.func_186060_c(ClientNetherDimensionHook.java:33) ~[?:0.3.2-BETA] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeWorldType.createChunkGenerator(IForgeWorldType.java:101) ~[?:?] {re:classloading}
	at voronoiaoc.byg.common.world.worldtype.BYGWorldType.createChunkGenerator(BYGWorldType.java:28) ~[?:0.3.2-BETA] {re:classloading}
	at net.minecraft.world.server.ServerWorld.lambda$new$3(ServerWorld.java:172) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.world.server.ServerWorld$$Lambda$6442/642014576.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.<init>(World.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.<init>(ServerWorld.java:171) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.world.server.ServerMultiWorld.<init>(ServerMultiWorld.java:17) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:412) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}`

**Comment by Voronoiii** [comment]
Thank you for providing the fix! This fix will not be made available until our 0.4.0 release. Until then our mods will clash. But we will put on the curse page that the mods are incompatible up until we release 0.4.0
